parameters:
  pool: ''

jobs:
  - job: ESLint
    pool:
      ${{ if eq(parameters.useOneEngineeringPool, 'true') }}:
        ${{ parameters.pool }}
      ${{ else }}:
        vmImage: ${{ parameters.pool.vmImage }}
    displayName: '🧶 ESLint'
    steps:
    - template: install-node.yaml
    - bash: |
        npm install --cache /temp/empty-cache
        npm install eslint@8.0.0 --reg https://registry.npmjs.org/ --verbose
        npm run lint
      displayName: 🧶 Run Lint
